name: Publish to FlakeHub

on:
  push:
    branches:
      - main
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-push@main
        with:
          visibility: public
          rolling: true
          extra-labels: |
            wallpaper
            catppuccin
            home-manager
            macos
            kde
